server:
  port: 18090
spring:
  jackson:
    time-zone: GMT+8
  profiles:
    active: dev
  application:
    name: kaykio-ai-service
logging:
  level:
    root: debug
  config: classpath:logback-spring.xml
log:
  path: /data/logs/api
  name: com.kaykip.api
  level: error
  logstore: api-service-dev